# Generated by Django 4.1 on 2022-09-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_profile_uid_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='complent',
            name='cfrom',
            field=models.CharField(max_length=255, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='complent',
            name='comfrom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sector'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, null=b'I01\n', upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.ForeignKey(default=1, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
