# Generated by Django 4.1 on 2022-09-14 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_student_image_alter_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departiment',
            old_name='title',
            new_name='colage',
        ),
        migrations.RemoveField(
            model_name='departiment',
            name='memberS',
        ),
        migrations.AddField(
            model_name='departiment',
            name='descr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departiment',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departiment',
            name='members',
            field=models.IntegerField(null=True),
        ),
    ]
