# Generated by Django 4.1 on 2022-09-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_student_radmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='depa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.departiment'),
        ),
        migrations.AddField(
            model_name='student',
            name='dorm',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
